# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
