# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190319_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
