# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190319_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(max_length=80, validators=[tweets.validators.validate_bad_content, tweets.validators.validate_blank_content]),
        ),
    ]
